# Generated by Django 3.2.8 on 2021-10-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_candidate_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
